# This is the configuration file for the brain reward model.

project_name: brain_reward_model
seed: 0 
ckpt_dir: ./checkpoints_rm

# data path <replace with your own paths>
datadir: <your_brain_data_dir>
split_csv_file: <your_brain_data_with_datasplit_file.csv>

# task
task: classification
combine_class_recon_splits: False
ignore_kspace: False
ignore_image: True
dataset: brain
coil_type: sc
classifier_type: arms
use_weighted_sampler: False 
train_sampler_filename: None
num_labels: 4
num_classes: 2
label_names: Edema,Enlarged ventricles,Mass,Abnormal
loss_type: cross_entropy 
class_weights: None
image_shape: [384, 384]
kspace_shape: [768, 400]
sampled_indices: [40, 359]
in_channels: 1

# backbone model
model_type: 'resnet50'
pretrained: imagenet
dropout: 0.1

# optimization
n_epochs: 400
num_workers: 3
optimizer: adamw
dropout_rate: 0.1
grad_clip_val: 0.0
batch_size: 32  
val_batch_size: 32
test_batch_size: 32
accumulate_grad_batches: 1
lr: 0.0001
weight_decay: 0.1
lr_step_size: 3
lr_gamma: 0.1
lr_scheduler: true
k_fraction: 0.1
center_fraction: 0.05
mask_type: vds
val_fn_type: MI
greedy_search: True
min_sampling_rate: 0.05
max_sampling_rate: 1.0
early_stopping_greedy: True
val_shuffle : False

# checkpoint
resume_train: False
ckpt_path: None